In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df=pd.read_csv('/content/drive/MyDrive/customer.csv')

In [5]:
df.sample(5)

,age,gender,review,education,purchased
25,57,Female,Good,School,No
8,65,Female,Average,UG,No
45,61,Male,Poor,PG,Yes
49,25,Female,Good,UG,No
14,15,Male,Poor,PG,Yes


In [ ]:
# gender is a nominal categorical variable

# review is ordinal categorical variable

# education is ordinal categorical variable

# age is numerical column

# purchased nominal categorical variable

* what you have to do is basically you have to seaparate gender and you have to put one hot encoder on it

* While you have to separate review and education and you have to put ordinal encoder on it and then you have to join it

* On purchase column we will apply label encoder

In [11]:
df=df[['review','education','purchased']]

In [12]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.3,random_state=0)

In [16]:
X_train

,review,education
7,Poor,School
14,Poor,PG
45,Poor,PG
48,Good,UG
29,Average,UG
15,Poor,UG
30,Average,UG
32,Average,UG
16,Poor,UG
42,Good,PG


In [17]:
Y_train

,purchased
7,Yes
14,Yes
45,Yes
48,Yes
29,Yes
15,No
30,No
32,Yes
16,Yes
42,Yes


In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [20]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

### **Transforming both X_train and X_test**

In [21]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [22]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [23]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.]])

### **Attributes for knowing categories**

In [24]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### **Applying Label Encoding on Purchased Column**

Label encoding is explicitly used for target columns and not for input columns

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le=LabelEncoder()

In [27]:
le.fit(Y_train)
# No is getting 0
# Yes is getting 1

LabelEncoder()

In [28]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [29]:
Y_train=le.transform(Y_train)
Y_test=le.transform(Y_test)

In [30]:
Y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [31]:
Y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0])